CXXFLAGS = -Wall -Wextra

helloTass: helloTass.o 
	$(LINK.cc) $^ -o $@

echoname: echoname.o
	$(LINK.cc) $^ -o $@

echoage: echoage.o
	$(LINK.cc) $^ -o $@

echoargs: echoargs.o
	$(LINK.cc) $^ -o $@

clean:
	rm -rf *.o program
