CXXFLAGS = -Wall -Wextra

overloading1: overloading1.o 
	$(LINK.cc) $^ -o $@

overloading2: overloading2.o 
	$(LINK.cc) $^ -o $@

overloading3: overloading3.o 
	$(LINK.cc) $^ -o $@

overloading4: overloading4.o 
	$(LINK.cc) $^ -o $@

clean:
	rm -rf *.o program
